<a href="https://colab.research.google.com/github/rishisaini1223/Advance_python/blob/main/numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [ ]:
a **2

array([ 1,  4,  9, 16])

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

- unique() ----> it will return 3 arrays.
- arr ----> return original values of array.
- return_index = True  ----> return index value of unique numbers.
- return_counts = True ----> it will return total freuency of each unique value

In [ ]:
a = np.array([1,2,2,2,3,3,3,4,4,4,5,5,5])
a

array([1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [ ]:
np.unique(a,return_index=True,return_counts=True)

(array([1, 2, 3, 4, 5]), array([ 0,  1,  4,  7, 10]), array([1, 3, 3, 3, 3]))

- hstack() and vstack()

- hstack() ----> it will add 2 or more arrays in harizontally.
- vstack() ----> it will add 2 or more arrays in vertically.

In [ ]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
c = np.arange(9,13).reshape(2,2)

In [ ]:
np.hstack((a,b,c))

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

In [ ]:
np.vstack((a,b,c))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
a

In [ ]:
# create an array (30,80) total elements 36  ----> reshape(2*18, 4*9, 6*6)

In [ ]:
a = np.random.randint(30,80,36).reshape((2,18))
a

array([[66, 55, 34, 34, 45, 39, 46, 31, 51, 48, 70, 77, 70, 34, 66, 32,
        39, 61],
       [31, 79, 73, 42, 30, 30, 71, 74, 42, 30, 34, 50, 33, 31, 58, 68,
        79, 58]])

In [ ]:
a = np.random.randint(30,80,36).reshape((4,9))
a

array([[58, 45, 76, 32, 70, 62, 78, 58, 31],
       [55, 64, 43, 50, 73, 61, 62, 30, 34],
       [53, 69, 63, 43, 47, 47, 37, 60, 54],
       [41, 64, 38, 63, 78, 35, 49, 43, 50]])

In [ ]:
a = np.random.randint(30,80,36).reshape((6,6))
a

array([[48, 73, 33, 39, 60, 68],
       [33, 52, 78, 35, 49, 74],
       [68, 70, 32, 68, 49, 55],
       [69, 43, 50, 38, 73, 51],
       [57, 78, 43, 66, 47, 67],
       [44, 58, 43, 74, 70, 55]])

In [27]:
a = np.arange(6,10)
b = np.arange(11,15)
a

array([6, 7, 8, 9])

In [29]:
np.hstack((a,b))

array([ 6,  7,  8,  9, 11, 12, 13, 14])